name: CI

on:
- push
- pull_request
- workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Python ${{ matrix.python }}
    strategy:
      matrix:
        python: ['3.12', '3.13-dev']
    steps:
      - uses: actions/checkout@v4
      - name: setup test environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: install pip
        run:
          python -m pip install --upgrade pip wheel
      - name: install for python 3.13
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          python -m pip install lxml
          python -m pip install --pre cffi  # https://github.com/pyca/cryptography/issues/10806
        if: ${{ matrix.python == '3.13-dev' }}
      - name: install package
        run:
          python -m pip install https://github.com/nexB/scancode-toolkit/archive/refs/heads/develop.zip
      - name: download archive
        run:
          python -m pip download --no-deps "typing_extensions==4.8.0"
      - name: unpack archive
        run: |
          mkdir package
          unzip *.whl -d package
      - name: run analysis
        run: |
          scancode -l --license-text --license-text-diagnostics --yaml output.yml package/
          cat output.yml
      - name: run in subprocess
        run: |
          python -c "import subprocess; import sys; subprocess.run(['scancode', '-l', '--license-text', '--license-text-diagnostics', '--yaml', 'output1.yml', 'package/'])"
          cat output1.yml
  
